options {
    directory "/var/bind";

    listen-on { any; };
    listen-on-v6 { any; };

    recursion yes;
    max-cache-size 32M;
    dnssec-validation auto;
    empty-zones-enable yes;

    allow-query { any; };
    allow-recursion { any; };
    allow-query-cache { any; };
    allow-transfer { none; };
};

zone "." IN {
    type hint;
    file "named.ca";
};

controls {};
